version: '3.3'
services:
  todo-rest-api:
    image: vayalankatil/dbdemo-multicontainer:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: sudheesh
      RDS_PASSWORD: dummy

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummy 
      MYSQL_USER: sudheesh
      MYSQL_PASSWORD: dummy
      MYSQL_DATABASE: todos
